import DashboardLayout from '../../app/layout/DashboardLayout'
import TaskSection from './TaskSection'
import NotesWorkspace from '../notes/NotesWorkspace'
import FocusPanel from '../tracking/FocusPanel'
import RightSidebar from './RightSidebar'

export default function Workspace({
  projects,
  currentProject,
  onProjectSwitch,
  onCreateProject,
  onRenameProject,
  onDeleteProject,
  onLinkFolder,
  onUnlinkFolder,
  tasks,
  activeTask,
  elapsed,
  isRunning,
  onStart,
  onStop,
  onTaskSelect,
  onTaskAdd,
  onTaskDone,
  onTaskBlock,
  onTaskEdit,
  onTaskDelete,
  onClearDoneUI,
  tasksCompleted,
  activeTaskCount,
  archivedTaskCount,
  timeToday,
  taskTotalFormatted,
  logs,
  onLog,
  onLogClear,
  notes,
  onNoteNew,
  onNoteChange,
  onNoteRename,
  onNoteDelete,
  onNoteSyncObsidian,
  onNoteImportFileList,
  commands,
  onCommandAdd,
  onCommandDelete,
  resources,
  onResourceAdd,
  onResourceDelete,
  globalTotalWorkspaces,
  globalArchivedTasks,
  globalTimeToday,
  activeView,
  onViewChange,
}) {
  return (
    <DashboardLayout
      projects={projects}
      currentProject={currentProject}
      onProjectSwitch={onProjectSwitch}
      onCreateProject={onCreateProject}
      onRenameProject={onRenameProject}
      onDeleteProject={onDeleteProject}
      onLinkFolder={onLinkFolder}
      onUnlinkFolder={onUnlinkFolder}
      activeTask={activeTask}
      activeView={activeView}
      onViewChange={onViewChange}
      leftPanel={
        <TaskSection
          tasks={tasks}
          onTaskSelect={onTaskSelect}
          onTaskAdd={onTaskAdd}
          onTaskDone={onTaskDone}
          onTaskBlock={onTaskBlock}
          onTaskEdit={onTaskEdit}
          onTaskDelete={onTaskDelete}
          onClearDoneUI={onClearDoneUI}
        />
      }
      centerPanel={
        <FocusPanel
          activeTask={activeTask}
          elapsed={elapsed}
          isRunning={isRunning}
          onStart={onStart}
          onStop={onStop}
          taskTotalFormatted={taskTotalFormatted}
          workspaceTimeToday={timeToday}
          tasksCompleted={tasksCompleted}
          globalTimeToday={globalTimeToday}
        />
      }
      rightPanel={
        <RightSidebar
          logs={logs}
          onLog={onLog}
          onLogClear={onLogClear}
          commands={commands}
          onCommandAdd={onCommandAdd}
          onCommandDelete={onCommandDelete}
          resources={resources}
          onResourceAdd={onResourceAdd}
          onResourceDelete={onResourceDelete}
        />
      }
      notesPanel={
        <NotesWorkspace
          key={currentProject?.id}
          notes={notes}
          onNew={onNoteNew}
          onChange={onNoteChange}
          onRename={onNoteRename}
          onDelete={onNoteDelete}
          onSyncObsidian={onNoteSyncObsidian}
          onImportFileList={onNoteImportFileList}
        />
      }
      footerProps={{
        tasksCompleted,
        activeTaskCount,
        archivedTaskCount,
        timeToday,
        globalTotalWorkspaces,
        globalArchivedTasks,
        globalTimeToday
      }}
    />
  )
}

